In [ ]:
import numpy as np

1.Create a 1D NumPy array with numbers from 1 to 10

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2.Create a 3×3 matrix with all zeros.

In [3]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3.Create a 4×4 identity matrix

In [5]:
c=np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


4.Print the 3rd element of an array

In [6]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(a[2])

3


5.Print the last element of an array.

In [9]:
print(a[-1 ])

10


6.Print elements from index 2 to 5.

In [10]:
print(a[2:5])

[3 4 5]


7.Print alternate elements.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[::2])

[1 3 5 7]


8.Create a 4×4 matrix: x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]) 8.1 Print the 2nd row. 8.2 Print the 3rd column. 8.3 Print the submatrix: [[6,7], [10,11]]

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[5 6 7 8]]


In [17]:
print(a[1:2])

[[5 6 7 8]]


In [23]:
print(a[0:,2])

[ 3  7 11 15]


In [25]:
print(a[1,1],a[1,2])

6 7


In [27]:
print(a[2,1])

10


9.Create an array from 1 to 12 and reshape it into: 9.1 3×4 matrix 9.2 2×6 matrix

In [34]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [35]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
print(a.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


10.Flatten any 3*3 matrix into a 1D array.

In [40]:


a = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
f = a.flatten()
print(f)

[1 2 3 4 5 6 7 8 9]
